import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { DashboardLayout } from "@/components/DashboardLayout";
import { PageHeading, Panel, Notice, money, usePermissions } from "@/components/WorkspaceUI";
import { Button } from "@/components/ui/button";
import { accountService, type Account } from "@/services/accountService";
import { ledgerService, type AccountLedgerHistory } from "@/services/ledgerService";
export default function AccountDetail() {
 const { id } = useParams(); const [account, setAccount] = useState<Account>(); const [history, setHistory] = useState<AccountLedgerHistory>(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const { canManage } = usePermissions();
 async function load() { if (!id) return; setLoading(true); const [a, h] = await Promise.all([accountService.getAccountById(id), ledgerService.getAccountLedgerHistory(id)]); if (a.success) setAccount(a.data); if (h.success) setHistory(h.data); setError(!a.success || !h.success ? "Could not load the complete account history. Please retry." : ""); setLoading(false); }
 useEffect(() => { void load(); }, [id]);
 async function toggle() { if (!account) return; setBusy(true); const r = await accountService.updateAccountStatus(account.id, account.status === "Active" ? "Frozen" : "Active"); setBusy(false); if (r.success) void load(); else setError(r.errors?.join(" ") ?? "Status change failed."); }
 return <DashboardLayout><div className="space-y-6"><Link to="/accounts" className="text-sm text-primary">← Accounts</Link>{error && <Notice>{error} <button className="underline" onClick={load}>Retry</button></Notice>}{loading ? <Notice>Loading account...</Notice> : account && <><PageHeading title={account.accountNumber} description={`${account.currency} · ${account.status} · Opened ${new Date(account.createdAt).toLocaleDateString()}`}>{canManage && account.status !== "Closed" && <Button variant="outline" disabled={busy} onClick={toggle}>{busy ? "Updating..." : account.status === "Active" ? "Freeze account" : "Unfreeze account"}</Button>}</PageHeading><Panel title="Current balance"><p className="text-4xl font-semibold">{money(account.cachedBalance, account.currency)}</p><p className="mt-3 text-sm text-muted-foreground">{account.status === "Frozen" ? "Payments to and from this account are paused." : "Use this account for transfers within your workspace."}</p></Panel><Panel title="Recent account activity"><div className="divide-y divide-border">{history?.entries.map(e => <div key={e.id} className="flex flex-wrap justify-between gap-3 py-4"><div>{e.transactionId ? <Link to={`/transactions/${e.transactionId}`} className="text-sm font-medium text-primary">{e.description || "View transaction"}</Link> : <p className="text-sm">{e.description || "Opening entry"}</p>}<p className="mt-1 text-xs text-muted-foreground">{new Date(e.postedAt).toLocaleString()}</p></div><span className="text-sm font-semibold">{e.debitAmount > 0 ? "+" : "−"}{money(e.debitAmount || e.creditAmount, e.currency)}</span></div>)}{!history?.entries.length && <p className="text-sm text-muted-foreground">No activity yet. Transfers involving this account will appear here.</p>}</div></Panel></>}</div></DashboardLayout>;
}
