import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { DashboardLayout } from "@/components/DashboardLayout";
import { PageHeading, Panel, Notice, money, usePermissions } from "@/components/WorkspaceUI";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { accountService, type Account } from "@/services/accountService";
export default function AccountsList() {
 const [accounts, setAccounts] = useState<Account[]>([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [creating, setCreating] = useState(false); const [show, setShow] = useState(false); const [name, setName] = useState(""); const [currency, setCurrency] = useState("USD"); const { canManage } = usePermissions();
 async function load() { setLoading(true); const r = await accountService.getAccounts(); if (r.success) { setAccounts(r.data ?? []); setError(""); } else setError(r.errors?.join(" ") ?? "Unable to load accounts."); setLoading(false); }
 useEffect(() => { void load(); }, []);
 async function create(e: React.FormEvent) { e.preventDefault(); setCreating(true); const r = await accountService.createAccount({ accountNumber: name.trim(), accountType: "Asset", currency }); setCreating(false); if (r.success) { setShow(false); setName(""); void load(); } else setError(r.errors?.join(" ") ?? "Unable to create account."); }
 const filtered = accounts.filter(a => (!status || a.status === status) && `${a.accountNumber} ${a.currency}`.toLowerCase().includes(search.toLowerCase()));
 return <DashboardLayout><div className="space-y-6"><PageHeading title="Accounts" description="See your balances and explore the activity behind them.">{canManage && <Button onClick={() => setShow(!show)}>Create account</Button>}</PageHeading>{error && <Notice>{error} <button onClick={load} className="underline">Retry</button></Notice>}
 {show && <Panel title="Create an operating account"><form onSubmit={create} className="space-y-4"><label className="block text-sm">Account name or number<Input required maxLength={50} value={name} onChange={e => setName(e.target.value)} className="mt-2" placeholder="e.g. Operating USD" /></label><label className="block text-sm">Currency<select className="ml-3 rounded border border-border bg-card p-2" value={currency} onChange={e => setCurrency(e.target.value)}>{["USD", "EUR", "GBP", "VND"].map(c => <option key={c}>{c}</option>)}</select></label><p className="text-sm text-muted-foreground">Your account starts at zero. You can transfer funds from another operating account in this workspace.</p><Button disabled={creating}>{creating ? "Creating..." : "Create account"}</Button></form></Panel>}
 <div className="flex flex-wrap gap-3"><Input className="max-w-sm" aria-label="Search accounts" placeholder="Search accounts or currency" value={search} onChange={e => setSearch(e.target.value)} /><select aria-label="Filter account status" value={status} onChange={e => setStatus(e.target.value)} className="rounded border border-border bg-card px-3"><option value="">All statuses</option><option>Active</option><option>Frozen</option><option>Closed</option></select></div>
 {loading ? <Notice>Loading accounts...</Notice> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(a => <Panel key={a.id}><div className="flex items-start justify-between gap-3"><Link to={`/accounts/${a.id}`} className="font-semibold text-primary">{a.accountNumber}</Link><span className="rounded bg-muted px-2 py-1 text-xs">{a.status}</span></div><p className="my-5 text-2xl font-semibold">{money(a.cachedBalance, a.currency)}</p><p className="text-xs text-muted-foreground">{a.accountType === "Asset" ? "Operating account" : `${a.accountType} account`}</p><Link className="mt-4 block text-sm text-primary" to={`/accounts/${a.id}`}>View account and activity →</Link></Panel>)}{!filtered.length && <Notice>{accounts.length ? "No accounts match your filters." : "No accounts yet. Create an account to organize your money."}</Notice>}</div>}</div></DashboardLayout>;
}
