import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { ArrowDownRight, ArrowRight, ArrowUpRight, FileText, Plus, ReceiptText, WalletCards } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { DashboardLayout } from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/contexts/AuthContext";
import { money } from "@/components/WorkspaceUI";
import { overviewService, type OverviewTransaction } from "@/services/overviewService";

function greeting() { const hour = new Date().getHours(); return hour < 12 ? "Good morning" : hour < 18 ? "Good afternoon" : "Good evening"; }

export default function Dashboard() {
  const { user } = useAuth();
  const overview = useQuery({ queryKey: ["overview"], queryFn: overviewService.get, retry: 1 });
  const data = overview.data;
  const hasActivity = !!data && (data.incomeThisMonth !== 0 || data.expensesThisMonth !== 0 || data.outstandingInvoiceCount > 0 || data.recentTransactions.length > 0);
  return <DashboardLayout><div className="space-y-7">
    <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-muted-foreground">{greeting()}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">{user?.companyName || "Your financial workspace"}</h1><p className="mt-2 text-sm text-muted-foreground">A clear view of cash, client income, and business spending.</p></div><div className="flex gap-2"><Button asChild variant="outline"><Link to="/expenses"><ReceiptText className="mr-2 h-4 w-4" />Add expense</Link></Button><Button asChild><Link to="/invoices?create=1"><Plus className="mr-2 h-4 w-4" />Create invoice</Link></Button></div></header>
    {overview.isError && <div role="alert" className="rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-sm">We couldn't load your financial overview. Your records have not changed. <button className="font-semibold underline" onClick={() => overview.refetch()}>Try again</button></div>}
    {overview.isLoading ? <DashboardSkeleton /> : data && <>
      <section aria-label="Financial overview" className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Current balance" value={money(data.currentBalance, data.currency)} icon={<WalletCards />} detail={`Across active ${data.currency} accounts`} /><Metric label="Income this month" value={money(data.incomeThisMonth, data.currency)} icon={<ArrowDownRight />} tone="positive" detail="Confirmed invoice payments" /><Metric label="Expenses this month" value={money(data.expensesThisMonth, data.currency)} icon={<ArrowUpRight />} detail="Posted business expenses" /><Metric label="Outstanding invoices" value={money(data.outstandingInvoices, data.currency)} icon={<FileText />} tone={data.overdueInvoiceCount > 0 ? "warning" : undefined} detail={`${data.outstandingInvoiceCount} open · ${data.overdueInvoiceCount} overdue`} /></section>
      {!hasActivity ? <section className="rounded-xl border border-dashed bg-card px-6 py-16 text-center"><WalletCards className="mx-auto h-9 w-9 text-muted-foreground" /><h2 className="mt-4 text-lg font-semibold">Your financial activity will appear here</h2><p className="mx-auto mt-2 max-w-lg text-sm text-muted-foreground">Create an invoice or record your first expense to start building a useful financial overview.</p><div className="mt-6 flex justify-center gap-2"><Button asChild variant="outline"><Link to="/clients">Add a client</Link></Button><Button asChild><Link to="/invoices?create=1">Create invoice</Link></Button></div></section> : <>
        <div className="grid gap-5 lg:grid-cols-[1.45fr_1fr]"><section className="rounded-xl border bg-card p-5"><div className="flex items-end justify-between"><div><h2 className="font-semibold">Cash flow</h2><p className="mt-1 text-sm text-muted-foreground">Confirmed income and posted expenses · last 6 months</p></div><p className={`text-sm font-semibold tabular-nums ${data.netCashFlowThisMonth >= 0 ? "text-emerald-600" : "text-destructive"}`}>{data.netCashFlowThisMonth >= 0 ? "+" : ""}{money(data.netCashFlowThisMonth, data.currency)} this month</p></div><div className="mt-6 h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.cashFlow}><defs><linearGradient id="income" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="hsl(var(--success))" stopOpacity={0.24}/><stop offset="95%" stopColor="hsl(var(--success))" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month" tickLine={false} axisLine={false} fontSize={12}/><YAxis tickLine={false} axisLine={false} fontSize={12} width={68}/><Tooltip formatter={(value) => money(Number(value), data.currency)} /><Area name="Income" type="monotone" dataKey="income" stroke="hsl(var(--success))" fill="url(#income)" strokeWidth={2}/><Area name="Expenses" type="monotone" dataKey="expenses" stroke="hsl(var(--foreground))" fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></section>
          <section className="rounded-xl border bg-card"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-semibold">Outstanding invoices</h2><p className="mt-1 text-xs text-muted-foreground">What clients still owe</p></div><Link className="text-sm font-semibold text-primary" to="/invoices">View all</Link></div>{data.outstandingItems.length ? <div className="divide-y">{data.outstandingItems.slice(0,5).map(invoice => <div key={invoice.id} className="flex items-center justify-between gap-4 px-5 py-4"><div className="min-w-0"><p className="truncate text-sm font-medium">{invoice.clientName}</p><p className={`mt-1 text-xs ${invoice.status === "Overdue" ? "text-destructive" : "text-muted-foreground"}`}>{invoice.invoiceNumber} · {invoice.status === "Overdue" ? "Overdue" : `Due ${new Date(invoice.dueDate).toLocaleDateString()}`}</p></div><div className="text-right"><p className="text-sm font-semibold tabular-nums">{money(invoice.outstandingAmount, invoice.currency)}</p><Link to={`/invoices?pay=${invoice.id}`} className="mt-1 inline-flex text-xs font-medium text-primary">Record payment</Link></div></div>)}</div> : <p className="px-5 py-12 text-center text-sm text-muted-foreground">No outstanding invoices.</p>}</section></div>
        <section className="rounded-xl border bg-card"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-semibold">Recent activity</h2><p className="mt-1 text-xs text-muted-foreground">Latest posted financial records</p></div><Link className="inline-flex items-center text-sm font-semibold text-primary" to="/transactions">All transactions <ArrowRight className="ml-1 h-4 w-4" /></Link></div>{data.recentTransactions.length ? <div className="divide-y">{data.recentTransactions.map(transaction => <TransactionRow key={transaction.id} transaction={transaction} />)}</div> : <p className="px-5 py-12 text-center text-sm text-muted-foreground">No financial activity yet.</p>}</section>
      </>}
    </>}
  </div></DashboardLayout>;
}

function Metric({ label, value, detail, icon, tone }: { label: string; value: string; detail: string; icon: React.ReactNode; tone?: "positive" | "warning" }) { return <div className="rounded-xl border bg-card p-5"><div className={`flex h-9 w-9 items-center justify-center rounded-lg bg-muted text-muted-foreground [&>svg]:h-4 [&>svg]:w-4 ${tone === "positive" ? "bg-emerald-500/10 text-emerald-600" : tone === "warning" ? "bg-amber-500/10 text-amber-600" : ""}`}>{icon}</div><p className="mt-5 text-xs font-medium text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold tabular-nums">{value}</p><p className="mt-2 text-xs text-muted-foreground">{detail}</p></div>; }
function TransactionRow({ transaction }: { transaction: OverviewTransaction }) { const incoming = transaction.type === "InvoicePayment"; const expense = transaction.type === "Expense"; return <Link to={`/transactions/${transaction.id}`} className="flex items-center justify-between gap-4 px-5 py-4 transition-colors hover:bg-muted/30"><div className="min-w-0"><p className="truncate text-sm font-medium">{transaction.description}</p><p className="mt-1 text-xs text-muted-foreground">{transaction.category || transaction.type} · {new Date(transaction.date).toLocaleDateString()}</p></div><p className={`whitespace-nowrap text-sm font-semibold tabular-nums ${incoming ? "text-emerald-600" : expense ? "text-foreground" : "text-muted-foreground"}`}>{incoming ? "+" : expense ? "−" : ""}{money(transaction.amount, transaction.currency)}</p></Link>; }
function DashboardSkeleton() { return <div role="status" aria-label="Loading financial overview" className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[0,1,2,3].map(i => <div key={i} className="h-40 animate-pulse rounded-xl bg-muted" />)}</div><div className="h-80 animate-pulse rounded-xl bg-muted" /></div>; }
