import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { DashboardLayout } from "@/components/DashboardLayout";
import { PageHeading, Panel, Notice, usePermissions } from "@/components/WorkspaceUI";
import { Button } from "@/components/ui/button";
import { reconciliationService, type ReconciliationRun } from "@/services/reconciliationService";
export default function ReconciliationHub() {
 const [runs, setRuns] = useState<ReconciliationRun[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const { canReconcile } = usePermissions();
 async function load() { setLoading(true); const r = await reconciliationService.getRuns(); if (r.success) setRuns(r.data ?? []); else setError(r.errors?.join(" ") ?? "Could not load reconciliation."); setLoading(false); } useEffect(() => { void load(); }, []);
 async function run() { setBusy(true); setError(""); const r = await reconciliationService.runReconciliation("Workspace record check"); setBusy(false); if (r.success) void load(); else setError(r.errors?.join(" ") ?? "Reconciliation failed. Try again."); }
 return <DashboardLayout><div className="space-y-6"><PageHeading title="Reconciliation" description="Check whether account balances match their recorded financial activity.">{canReconcile && <Button disabled={busy} onClick={run}>{busy ? "Checking records..." : "Start reconciliation"}</Button>}</PageHeading><Notice>This checks records within Tenvora. External bank statements are not imported. Discrepancies can be investigated here; automatic correction is not available.</Notice>{error && <Notice>{error} <button className="underline" onClick={load}>Retry</button></Notice>}{loading ? <Notice>Loading previous checks...</Notice> : !runs.length ? <Notice>No checks yet. Start a reconciliation to see whether your records match.</Notice> : runs.map((r, i) => <Panel key={r.id} title={`${i === 0 ? "Latest check · " : ""}${r.discrepancyCount ? `${r.discrepancyCount} discrepancies need attention` : "Everything matches"}`}><p className="text-sm text-muted-foreground">{r.totalAccountsChecked} accounts checked · {new Date(r.startedAt).toLocaleString()}</p>{r.discrepancies.length > 0 && <div className="mt-4 divide-y divide-border">{r.discrepancies.map(d => <div key={d.id} className="py-4"><Link to={`/accounts/${d.accountId}`} className="text-sm font-semibold text-primary">{d.accountNumber || "Inspect affected account"} →</Link><p className="mt-2 text-sm">Recorded balance: {d.expectedBalance.toLocaleString(undefined, { maximumFractionDigits: 4 })} · Activity balance: {d.calculatedBalance.toLocaleString(undefined, { maximumFractionDigits: 4 })}</p><p className="mt-1 text-sm text-muted-foreground">Difference: {d.discrepancyAmount.toLocaleString(undefined, { maximumFractionDigits: 4 })} in the account currency. Inspect the account history to identify missing or incorrect activity.</p></div>)}</div>}</Panel>)}</div></DashboardLayout>;
}
