"""Compile reviewed JSON catalogs into Dart; requires only Python's standard library."""
from pathlib import Path
import json,re,sys

root=Path(__file__).resolve().parents[1]/'lib/core/localization'
catalogs={path.stem:json.loads(path.read_text(encoding='utf-8')) for path in sorted(root.glob('*.json'))}
english=catalogs['en']
for code,catalog in catalogs.items():
    assert set(catalog)==set(english),f'{code}: missing or extra keys'
    for key,value in catalog.items():
        assert isinstance(value,str) and value.strip(),f'{code}: empty {key}'
        assert sorted(re.findall(r'\{\w+\}',key))==sorted(re.findall(r'\{\w+\}',value)),f'{code}: placeholders in {key}'
        assert re.findall(r'https://\S+',key)==re.findall(r'https://\S+',value),f'{code}: altered URL in {key}'
def dart(value): return json.dumps(value,ensure_ascii=False).replace('$',r'\$')
lines=['// Generated by tool/generate_language_catalog.py. Edit the JSON catalogs instead.',
       '// ignore_for_file: prefer_single_quotes',
       'const Map<String, Map<String, String>> languageCatalogs = {']
for code,catalog in catalogs.items():
    lines.append('  '+dart(code)+': {')
    lines.extend('    '+dart(key)+': '+dart(value)+',' for key,value in catalog.items())
    lines.append('  },')
lines.append('};')
generated='\n'.join(lines)+'\n'
if '--check' in sys.argv:
    # Dart formatting may wrap lines; whitespace outside strings is immaterial.
    tokens=lambda text: re.findall(r'"(?:\\.|[^"\\])*"|\S',text)
    assert tokens(generated)==tokens((root/'catalog.g.dart').read_text(encoding='utf-8')), 'Generated Dart catalog is stale; regenerate and format it.'
else:
    (root/'catalog.g.dart').write_text(generated,encoding='utf-8')
print(f'Validated and generated {len(catalogs)} catalogs with {len(english)} strings each.')
