import { useEffect, useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { DashboardLayout } from "@/components/DashboardLayout";
import { PageHeading, Panel, Notice, money, usePermissions } from "@/components/WorkspaceUI";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { paymentService, type Transaction } from "@/services/paymentService";
import { accountService, type Account } from "@/services/accountService";
export default function Transfers() {
 const navigate = useNavigate(); const [params] = useSearchParams(); const { canManage } = usePermissions();
 const [accounts, setAccounts] = useState<Account[]>([]); const [payments, setPayments] = useState<Transaction[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [show, setShow] = useState(params.has("new")); const [review, setReview] = useState(false); const [busy, setBusy] = useState(false); const [source, setSource] = useState(""); const [destination, setDestination] = useState(""); const [amount, setAmount] = useState(""); const [reference, setReference] = useState(""); const [key, setKey] = useState(crypto.randomUUID());
 async function load() { setLoading(true); const [a, p] = await Promise.all([accountService.getAccounts(), paymentService.getTransactions(undefined, 100)]); if (a.success) setAccounts(a.data ?? []); if (p.success) setPayments((p.data ?? []).filter(t => t.transactionType === "Transfer")); if (!a.success || !p.success) setError("Unable to load payments or accounts. Please refresh."); setLoading(false); }
 useEffect(() => { void load(); }, []);
 const eligible = accounts.filter(a => a.status === "Active" && a.accountType === "Asset"); const from = eligible.find(a => a.id === source); const to = eligible.find(a => a.id === destination);
 function prepare(e: React.FormEvent) { e.preventDefault(); if (!from || !to || source === destination || from.currency !== to.currency || !Number.isFinite(Number(amount)) || Number(amount) <= 0 || Number(amount) > from.cachedBalance || !/^\d+(\.\d{1,4})?$/.test(amount)) { setError("Choose two different active accounts in the same currency and an amount within the available balance (up to four decimal places)."); return; } setError(""); setReview(true); }
 async function submit() { if (!from || busy) return; setBusy(true); setError(""); const r = await paymentService.executeTransfer(key, { sourceAccountId: source, destinationAccountId: destination, amount: Number(amount), currency: from.currency, purpose: reference || undefined }); setBusy(false); if (r.success && r.data?.transactionId) navigate(`/transactions/${r.data.transactionId}`); else setError(r.errors?.join(" ") ?? "Payment could not be confirmed. Retry with the same details."); }
 function edit() { setReview(false); setKey(crypto.randomUUID()); }
 return <DashboardLayout><div className="space-y-6"><PageHeading title="Internal Allocations" description="Reclassify recorded balances between categories in your workspace.">{canManage && <Button onClick={() => { setShow(true); }}>Create allocation</Button>}</PageHeading>{error && <Notice>{error}</Notice>}
 {show && canManage && <Panel title={review ? "Review allocation" : "Create allocation"}><p className="mb-5 text-sm text-muted-foreground">{review ? "Check the details before confirming. This updates internal workspace records immediately." : "Allocations stay inside this workspace. External bank payments are not connected."}</p>{review && from && to ? <div className="max-w-xl space-y-5"><p className="text-4xl font-semibold">{money(Number(amount), from.currency)}</p><dl className="grid grid-cols-2 gap-3 text-sm"><dt>From</dt><dd>{from.accountNumber}</dd><dt>To</dt><dd>{to.accountNumber}</dd><dt>Reference</dt><dd className="break-words">{reference || "No reference"}</dd></dl><div className="flex gap-3"><Button variant="outline" disabled={busy} onClick={edit}>Edit details</Button><Button disabled={busy} onClick={submit}>{busy ? "Recording allocation..." : "Confirm allocation"}</Button></div></div> : <form onSubmit={prepare} className="max-w-xl space-y-4"><label className="block text-sm">From<select required value={source} onChange={e => { setSource(e.target.value); setDestination(""); }} className="mt-2 block w-full rounded-md border border-border bg-card p-3"><option value="">Select source category</option>{eligible.map(a => <option key={a.id} value={a.id}>{a.accountNumber} · {money(a.cachedBalance, a.currency)}</option>)}</select></label><label className="block text-sm">To<select required value={destination} onChange={e => setDestination(e.target.value)} className="mt-2 block w-full rounded-md border border-border bg-card p-3"><option value="">Select destination category</option>{eligible.filter(a => a.id !== source && a.currency === from?.currency).map(a => <option key={a.id} value={a.id}>{a.accountNumber}</option>)}</select></label><label className="block text-sm">Amount {from?.currency}<Input className="mt-2" required inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)} placeholder="0.00" /></label><label className="block text-sm">Reference (optional)<Input className="mt-2" maxLength={500} value={reference} onChange={e => setReference(e.target.value)} placeholder="What is this allocation for?" /></label><div className="flex gap-3"><Button type="button" variant="outline" onClick={() => setShow(false)}>Cancel</Button><Button disabled={loading}>Review allocation</Button></div></form>}</Panel>}
 <Panel title="Recent allocations"><p className="mb-4 text-xs text-muted-foreground">Most recent 100 internal transfer records</p>{loading ? <Notice>Loading allocations...</Notice> : payments.length ? <div className="divide-y divide-border">{payments.map(p => <Link key={p.id} to={`/transactions/${p.id}`} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="text-sm font-medium">{p.description || p.referenceNumber}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(p.createdAt).toLocaleString()} · {p.referenceNumber}</p></div><div className="text-right"><p className="text-sm font-semibold">{money(p.amount, p.currency)}</p><p className="mt-1 text-xs text-muted-foreground">{p.status === "Posted" ? "Recorded" : p.status}</p></div></Link>)}</div> : <p className="text-sm text-muted-foreground">No allocations yet. Create one to reclassify recorded balances.</p>}</Panel></div></DashboardLayout>;
}
