import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { DashboardLayout } from "@/components/DashboardLayout";
import { PageHeading, Panel, Notice, money } from "@/components/WorkspaceUI";
import { Input } from "@/components/ui/input";
import { paymentService, type Transaction } from "@/services/paymentService";
export default function TransactionsList() {
 const [rows, setRows] = useState<Transaction[]>([]); const [query, setQuery] = useState(""); const [status, setStatus] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
 async function load() { setLoading(true); const r = await paymentService.getTransactions(undefined, 500); if (r.success) { setRows(r.data ?? []); setError(""); } else setError(r.errors?.join(" ") ?? "Unable to load transactions."); setLoading(false); } useEffect(() => { void load(); }, []);
 const filtered = rows.filter(t => (!status || t.status === status) && `${t.referenceNumber} ${t.description} ${t.currency}`.toLowerCase().includes(query.toLowerCase()));
 return <DashboardLayout><div className="space-y-6"><PageHeading title="Transactions" description="Inspect completed payments, reversals, and settlement records. Showing the latest 500 records." />{error && <Notice>{error} <button onClick={load} className="underline">Retry</button></Notice>}<div className="flex flex-wrap gap-3"><Input className="max-w-sm" aria-label="Search transactions" placeholder="Search reference or currency" value={query} onChange={e => setQuery(e.target.value)} /><select aria-label="Transaction status" className="rounded border border-border bg-card p-2" value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option><option value="Posted">Completed</option><option>Settled</option><option>Reversed</option><option>Failed</option></select></div><Panel>{loading ? <Notice>Loading transactions...</Notice> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="text-muted-foreground"><th className="p-3">Reference</th><th className="p-3">Amount</th><th className="p-3">Status</th><th className="p-3">Type</th><th className="p-3">Date</th></tr></thead><tbody>{filtered.map(t => <tr key={t.id} className="border-t border-border"><td className="p-3"><Link className="font-medium text-primary" to={`/transactions/${t.id}`}>{t.description || t.referenceNumber}</Link><p className="mt-1 text-xs text-muted-foreground">{t.referenceNumber}</p></td><td className="whitespace-nowrap p-3">{money(t.amount, t.currency)}</td><td className="p-3">{t.status === "Posted" ? "Completed" : t.status}</td><td className="p-3">{t.transactionType}</td><td className="whitespace-nowrap p-3">{new Date(t.createdAt).toLocaleString()}</td></tr>)}</tbody></table>{!filtered.length && <p className="p-5 text-sm text-muted-foreground">No transactions match. Your payment activity will appear here.</p>}</div>}</Panel></div></DashboardLayout>;
}
