import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { DashboardLayout } from "@/components/DashboardLayout";
import { PageHeading, Panel, Notice, money, usePermissions } from "@/components/WorkspaceUI";
import { Button } from "@/components/ui/button";
import { settlementService, type SettlementBatch } from "@/services/settlementService";
export default function SettlementBatches() {
 const [batches, setBatches] = useState<SettlementBatch[]>([]); const [currency, setCurrency] = useState("USD"); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [confirm, setConfirm] = useState<string>(); const { canManage } = usePermissions();
 async function load() { setLoading(true); const r = await settlementService.getBatches(); if (r.success) setBatches(r.data ?? []); else setError(r.errors?.join(" ") ?? "Could not load settlements."); setLoading(false); } useEffect(() => { void load(); }, []);
 async function create() { setBusy(true); setError(""); const r = await settlementService.createBatch(currency); setBusy(false); if (r.success) void load(); else setError(r.errors?.join(" ") ?? "Batch creation failed."); }
 async function settle(id: string) { setBusy(true); setError(""); const r = await settlementService.settleBatch(id); setBusy(false); if (r.success) { setConfirm(undefined); void load(); } else setError(r.errors?.join(" ") ?? "Settlement failed."); }
 return <DashboardLayout><div className="space-y-6"><PageHeading title="Settlements" description="Group completed payments, inspect the batch, and finalize your internal settlement records." /><Notice>Settlement records organize transfers within Tenvora. Finalizing a batch does not send a payout to a bank.</Notice>{error && <Notice>{error}</Notice>}{canManage && <Panel title="Prepare a batch"><div className="flex flex-wrap gap-3"><select aria-label="Settlement currency" className="rounded border border-border bg-card p-2" value={currency} onChange={e => setCurrency(e.target.value)}>{["USD", "EUR", "GBP", "VND"].map(c => <option key={c}>{c}</option>)}</select><Button disabled={busy} onClick={create}>{busy ? "Saving..." : "Prepare settlement batch"}</Button></div><p className="mt-3 text-sm text-muted-foreground">Includes completed transactions in this currency that have not already been assigned to a batch.</p></Panel>}
 {loading ? <Notice>Loading settlement batches...</Notice> : !batches.length ? <Notice>No settlement batches yet. Prepare a batch after completing your first payment.</Notice> : batches.map(b => <Panel key={b.id}><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">{b.batchNumber}</h2><p className="mt-2 text-sm text-muted-foreground">{b.totalTransactions} transactions · {b.status} · Created {new Date(b.createdAt).toLocaleString()}</p>{b.settledAt && <p className="mt-1 text-sm text-muted-foreground">Finalized {new Date(b.settledAt).toLocaleString()}</p>}</div><p className="text-2xl font-semibold">{money(b.totalDebitAmount, b.currency)}</p></div><details className="mt-5"><summary className="cursor-pointer text-sm text-primary">Inspect included transactions</summary><div className="mt-3 divide-y divide-border">{b.transactions?.map(t => <Link key={t.id} className="flex justify-between gap-3 py-3 text-sm" to={`/transactions/${t.id}`}><span className="text-primary">{t.referenceNumber} · {t.status === "Posted" ? "Completed" : t.status}</span><span>{money(t.amount, b.currency)}</span></Link>)}</div></details>{b.status === "Open" && canManage && <div className="mt-5">{confirm === b.id ? <div className="space-y-3"><p className="text-sm">Finalize {b.totalTransactions} transactions totaling {money(b.totalDebitAmount, b.currency)}?</p><Button disabled={busy} onClick={() => settle(b.id)}>Confirm settlement</Button><Button className="ml-2" variant="outline" disabled={busy} onClick={() => setConfirm(undefined)}>Cancel</Button></div> : <Button variant="outline" onClick={() => setConfirm(b.id)}>Finalize batch</Button>}</div>}</Panel>)}</div></DashboardLayout>;
}
